import "./globals.css";
import "./animations.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const luckiestGuy = localFont({
  src: "../public/fonts/LuckiestGuy-Regular.ttf",
  weight: "normal", // specify the correct weight
  style: "normal", // specify the correct style
  variable: "--font-luckiestguy",
});

const maladroit = localFont({
  src: "../public/fonts/CCMaladroitRegular.ttf",
  weight: "normal", // specify the correct weight
  style: "normal", // specify the correct style
  variable: "--font-maladroit",
});

const yantramanavRegular = localFont({
  src: "../public/fonts/Yantramanav-Regular.ttf",
  weight: "normal", // specify the correct weight
  style: "normal", // specify the correct style
  variable: "--font-yantramanav-r",
});

const yantramanavMedium = localFont({
  src: "../public/fonts/Yantramanav-Medium.ttf",
  weight: "semibold", // specify the correct weight
  style: "semibold", // specify the correct style
  variable: "--font-yantramanav-sb",
});

const yantramanavBold = localFont({
  src: "../public/fonts/Yantramanav-Black.ttf",
  weight: "bold", // specify the correct weight
  style: "bold", // specify the correct style
  variable: "--font-yantramanav-b",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${luckiestGuy.variable} ${maladroit.variable} ${yantramanavRegular.variable} ${yantramanavMedium.variable} ${yantramanavBold.variable}`}
    >
      <body className="font-maladroit-regular">{children}</body>
    </html>
  );
}
